#!/usr/bin/env bash

TIME=$(date +%k:%M:%S)
TODAY=$(date +"%A %B %d, %Y")
TODAY_ISO8601=$(date +"%Y%m%d")

CURRENT_TIME=`date +%H`

if [ $CURRENT_TIME -lt 12 ]; then
  GREETING="Good morning"
elif [ $CURRENT_TIME -lt 18 ]; then
  GREETING="Good afternoon"
else
  GREETING="Good evening"
fi

echo -e "$GREETING, $(whoami)!" | lolcat
echo -e "Today is $TODAY\n" | lolcat
echo -e "the time is now $TIME" | lolcat

# print a fortune when the terminal opens
fortune -a -s | cowsay | lolcat
echo -e "\n"
