#!/usr/bin/env bash
# -*- coding: utf-8 -*- 

$if Bash
  Space: magic-space
$endif


set show-all-if-ambiguous on
set show-all-if-unmodified on
set bell-style none
set menu-complete-display-prefix on
set visible-stats on
set colored-stats on
set expand-tilde off
set show-all-if-ambiguous on
set completion-ignore-case on

# Immediately add a trailing slash when autocompleting symlinks to directories
set mark-symlinked-directories on
set completion-query-items 200
set skip-completed-text on
set input-meta on
set output-meta on
set convert-meta off

# \C- means Ctrl plus another key
# \M- means Meta (Option) plus another key
# \e is the ESC character
# \\ is a backslash
# \" is a double quote
# \' is a single quote


"\M-o": "\C-p\C-a\M-f "
"\M-s": menu-complete


#This will let you to begin a command and hit the up-arrow
#to search backwards through your history for commands starting
#with whatever you've typed so far
# Use the text that has already been typed as the prefix for searching through
# commands (i.e. more intelligent Up/Down behavior)

"\eOA": history-search-backward
"\e[A": history-search-backward
"\eOB": history-search-forward
"\e[B": history-search-forward
"\eOC": forward-char
"\e[C": forward-char
"\eOD": backward-char
"\e[D": backward-char

# Do not autocomplete hidden files unless the pattern explicitly begins with a dot
set match-hidden-files off

# use alt/option key to jump b/w words. 
"\e[1;5C": forward-word
"\e[1;5D": backward-word

# not totally sure what these do differently
# "\e[1;5C": shell-forward-word
# "\e[1;5D": shell-backward-word

"\e[3~": kill-word
