#!/usr/bin/env bash

# I don't know what this does
export CLICOLOR=1

# Don't put duplicate lines in your bash history
export HISTCONTROL=ignoredups

# boost history limit (100KB or 5K entries)
export HISTFILESIZE=100000
export HISTSIZE=5000

# private stuff kept off of github for security
source ~/.privaterc


function parse_git_dirty() {
  [[ $(git status 2> /dev/null | tail -n1) != *"working directory clean"* ]] && echo "*"
}

function parse_git_branch() {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1$(parse_git_dirty)/"
}
