#!/usr/bin/env Rscript

r <- getOption("repos")             
r["CRAN"] <- "http://cran.us.r-project.org"
options(repos = r)
rm(r)

# options(repos=structure(c(CRAN="YOUR FAVORITE MIRROR")))
options(stringsAsFactors = FALSE)
options(useFancyQuotes = FALSE)

print(paste("OPTIONS COORDSYS(", dQuote("Surface 1"), "AS COMPONENT);"),quote=F)



