#!/usr/bin/env bash
# -*- coding: utf-8 -*- 

export _Z_NO_RESOLVE_SYMLINKS=1

# Move next only if `homebrew` is installed
if command -v brew >/dev/null 2>&1; then
    # Load rupa's z if installed
    [ -f $(brew --prefix)/etc/profile.d/z.sh ] && source $(brew --prefix)/etc/profile.d/z.sh
fi
