#!/usr/bin/env bash

cleanup() {
    # delete files and directories matching these patterns
    local patterns=('.pyc' '.DS_Store' '__MACOSX')
    local dirs=('__pycache__')

    for pattern in "${patterns[@]}"; do
        echo "Searching for and deleting files matching $pattern"
        # Use find to search for files matching the pattern and delete them
        find . -type f -name "$pattern" -exec rm -rf {} +
    done

    for dir in "${dirs[@]}"; do
        echo "Searching for and deleting directories matching $dir"
        # Use find to search for directories and delete them
        find . -type d -name "$dir" -exec rm -rf {} +
    done

    echo "Cleanup completed."
}
